InBound/urls.py
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.contrib.auth import views
from user.forms import LoginForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('user.urls')),
    url(r'product/', include('product.urls')),
    url(r'supplier/', include('product.urls')),
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm},name='login'),  
    url(r'^logout/$', views.logout, {'next_page': '/login'}),  
]


if settings.DEBUG:
    urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

product/urls.py
# log/urls.py
from django.conf.urls import url
from . import views

app_name = 'product'

# We are adding a URL called /home
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.create, name='create'),
    url(r'^manage/$', views.manage, name='manage'),
    url(r'^edit/(?P<pk>\d+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<pk>\d+)/$', views.delete_product, name='delete_product'),
    url(r'^category/$', views.create_category, name='create_category'),
    url(r'^category/manage/$', views.manage_category, name='manage_category'),
    url(r'^category/edit/(?P<pk>\d+)/$', views.edit_category, name='edit_category'),
    url(r'^category/delete/(?P<pk>\d+)/$', views.delete_category, name='delete_category'),
    url(r'^supplier/$', views.create_supplier, name='create_supplier'),
    url(r'^supplier/edit/(?P<pk>\d+)/$', views.edit_supplier, name='edit_supplier'),
    url(r'^supplier/manage/$', views.manage_supplier, name='manage_supplier'),
    url(r'^category/delete/(?P<pk>\d+)/$', views.delete_supplier, name='delete_supplier'),
]

user/urls.py
# log/urls.py
from django.conf.urls import url
from . import views

# We are adding a URL called /home
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

product/models.py
from django.db import models


# Create your models here.

class Category(models.Model):
    cat_name = models.CharField(max_length=30)
    cat_description = models.TextField()
    isActive = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_date = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.cat_name


class Supplier(models.Model):
    company_name = models.CharField(max_length=50)
    agency_name = models.CharField(max_length=50,null=True,blank=True)
    full_name = models.CharField(max_length=50)
    email = models.TextField(max_length=50)
    phone_number = models.TextField(max_length=20)
    address1 = models.TextField(max_length=50)
    address2 = models.TextField(max_length=50,null=True,blank=True)
    city = models.TextField(max_length=50)
    state = models.TextField(max_length=50)
    zip = models.TextField(max_length=50)
    country = models.TextField(max_length=50)
    comments = models.TextField(max_length=50,null=True,blank=True)

    def __str__(self):
        return self.company_name


class Item(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField()
    barcode = models.IntegerField(null=True)
    isActive = models.BooleanField(default=True)
    category = models.ForeignKey(Category, null=True)
    stock_count = models.IntegerField()
    supplier = models.ForeignKey(Supplier, null=True)
    created_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_date = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.title

product/forms.py
# make sure this is at the top if it isn't already
from django import forms
from .models import Item, Category, Supplier


# our new form
class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('title', 'description', 'barcode', 'stock_count', 'isActive', 'category','supplier')
        labels = {
            'isActive': 'Enable Product',
        }
        widgets = {
            "title": forms.TextInput(attrs={'placeholder': 'Product Name', 'id': 'title', 'class': 'md-input'}),
            "description": forms.TextInput(
                attrs={'placeholder': 'Description', 'id': 'Description', 'class': 'md-input'}),
            "stock_count": forms.NumberInput(
                attrs={'placeholder': 'Enter Stock', 'class': 'md-input'}),
            "barcode": forms.TextInput(attrs={'placeholder': 'UPC/EAN/ISBN', 'id': 'barcode', 'class': 'md-input'}),
            "isActive": forms.CheckboxInput(
                attrs={'placeholder': 'Enable', 'id': 'activeswitch', 'class': 'md-switch'}),
        }

    class Media:
        js = ('product/js/product.js',)

    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['barcode'].required = False


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('cat_name', 'cat_description')
        labels = {
            'cat_name': 'Category Name',
            'cat_description': 'Category Description'
        }
        widgets = {
            'cat_name': forms.TextInput(attrs={'placeholder': 'Category', 'id': 'cate_name', 'class': 'md-input'}),
            'cat_description': forms.TextInput(
                attrs={'placeholder': 'Description', 'id': 'Description', 'class': 'md-input'}),
        }


class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        agency_name = forms.CharField(required=False)
        email = forms.EmailField(widget=forms.EmailInput())

        # TODO implement phone number field
        fields = ('company_name', 'agency_name', 'full_name', 'email', 'phone_number','address1','address2', 'city',
                  'state', 'zip','country','comments')
        labels = {
            'address1': 'Address 1',
            'address2': 'Address 2',
        }
        widgets = {
            "company_name": forms.TextInput(attrs={'placeholder': 'Company Name', 'class': 'md-input'}),
            "agency_name": forms.TextInput(attrs={'placeholder': 'Agency Name', 'class': 'md-input'}),
            "full_name": forms.TextInput(attrs={'placeholder': 'Full Name', 'class': 'md-input'}),
            "email": forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'md-input'}),
            "phone_number": forms.NumberInput(attrs={'placeholder': 'Phone Number', 'class': 'md-input'}),
            "address1": forms.TextInput(attrs={'placeholder': 'Address 1', 'class': 'md-input'}),
            "address2": forms.TextInput(attrs={'placeholder': 'Address 2', 'class': 'md-input'}),
            "city": forms.TextInput(attrs={'placeholder': 'Enter City Name', 'class': 'md-input'}),
            "state": forms.TextInput(attrs={'placeholder': 'Enter State Name', 'class': 'md-input'}),
            "zip": forms.TextInput(attrs={'placeholder': 'Enter Zip Code', 'class': 'md-input'}),
            "country": forms.TextInput(attrs={'placeholder': 'Enter Country', 'class': 'md-input'}),
            "comments": forms.TextInput(attrs={'placeholder': 'Enter Comments', 'class': 'md-input'}),
        }

        def __init__(self, *args, **kwargs):
            super(SupplierForm, self).__init__(*args, **kwargs)
            self.fields['agency_name'].required = False
            self.fields['address2'].required = False
            self.fields['comments'].required = False

product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from .forms import ItemForm, CategoryForm ,SupplierForm
from .tables import ItemTable ,CategoryTable ,SupplierTable
from .models import Item, Category ,Supplier
from django.contrib import messages


def index(request):
    return render(request, 'product/create.html')


def create(request):
    if request.method == "POST":
        form = ItemForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.title = request.POST.get('title')
            item.description = request.POST.get('description')
            item.save()
            messages.success(request, 'Product Added')
            return redirect('product:manage')
    else:
        form = ItemForm()
        return render(request, 'product/create_form.html', {'form': form})


def manage(request):
    item = ItemTable()
    return render(request, "product/manage.html", {'item': item})


def edit(request, pk):
    item = get_object_or_404(Item, pk=pk)
    if request.method == "POST":
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            item = form.save(commit=False)
            item.title = request.POST.get('title')
            item.description = request.POST.get('description')
            item.save()
            messages.success(request, 'Product Edited')
            return redirect('product:manage')
    else:
        form = ItemForm(instance=item)
        return render(request, 'product/edit.html', {'form': form})


def delete_product(request,pk):
    item = get_object_or_404(Item, pk=pk)
    item.delete()
    messages.success(request, 'Product Deleted')
    return redirect('product:manage')


def create_category(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.save()
            messages.success(request, 'Category Added')
            return redirect('product:manage_category')
    else:
        form = CategoryForm()
        return render(request, "product/category_create.html", {'form': form})


def edit_category(request,pk):
    item = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=item)
        if form.is_valid():
            item = form.save(commit=False)
            item.save()
            messages.success(request, 'Category Edited')
            return redirect('product:manage_category')
    else :
        form = CategoryForm(instance=item)
        return render(request, "product/category_edit.html", {'form': form})


def manage_category(request):
    item = CategoryTable()
    return render(request, "product/manage_category.html", {'item': item})


def delete_category(request,pk):
    item = get_object_or_404(Category, pk=pk)
    item.delete()
    messages.success(request, 'Category Deleted')
    return redirect('product:manage_category')


def create_supplier(request):
    if request.method == "POST":
        form = SupplierForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.save()
            messages.success(request, 'Supplier Added')
            return redirect('product:manage_supplier')
    else:
        form = SupplierForm()
        return render(request, "product/create_supplier.html", {'form': form})


def edit_supplier(request,pk):
    item = get_object_or_404(Supplier, pk=pk)
    if request.method == "POST":
        form = SupplierForm(request.POST, instance=item)
        if form.is_valid():
            item = form.save(commit=False)
            item.save()
            messages.success(request, 'Category Edited')
            return redirect('product:manage_supplier')
    else :
        form = SupplierForm(instance=item)
        return render(request, "product/edit_supplier.html", {'form': form})


def manage_supplier(request):
    item = SupplierTable()
    return render(request, "product/manage_supplier.html", {'item': item})


def delete_supplier(request,pk):
    item = get_object_or_404(Supplier, pk=pk)
    item.delete()
    messages.success(request, 'Category Deleted')
    return redirect('product:manage_supplier')

product/templates/product/category_create.html
{% extends 'base.html' %}
{% block title %}Create Category{% endblock %}


	{% block content %}
  
	<div class="padding">
  		<div class="row">
  	 <div  class="col-md-10">
    
      {% if messages %}
  
        {% for message in messages %}
        <script type="text/javascript">
        $(function(){
          
            $.notify("{{ message }}", { showProgressbar: false,type: 'success' });
         
        });
        </script>
        {% endfor %}

      {% endif %}


      <div class="box">
        <div class="box-header">
          <h2>Create Category</h2>
          <small>Create New Category , To Associate With Products</small>
          <!-- <button class="md-btn md-raised m-b-sm w-xl green pull-right">Add Category</button> -->
        </div>
        <div class="box-divider m-a-0"></div>
        <div class="box-body">
          <form role="form" method="post">
          {% csrf_token %}
             {{ form.as_p }}
             <div class="form-group row m-t-lg">
              <div class="col-sm-4 col-sm-offset-2">
                <button type="button" class="btn white">Cancel</button>
                <button type="submit" class="btn primary">Save</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  		</div>
  	</div>
  
 {% block scripts %}
      {{ block.super }}    
      {{ form.media }}     
  {% endblock %}

  <script type="text/javascript">
  $(function(){

    $("#activeswitch").Sswitch({
      onSwitchChange: function() {
      }
    });  
  });

  </script>

  {% endblock %}

product/templates/product/category_edit.html
{% extends 'base.html' %}
{% block title %}Edit Category{% endblock %}


	{% block content %}
  
	<div class="padding">
  		<div class="row">
  	 <div  class="col-md-10">
    
      {% if messages %}
  
        {% for message in messages %}
        <script type="text/javascript">
        $(function(){
          
            $.notify("{{ message }}", { showProgressbar: false,type: 'success' });
         
        });
        </script>
        {% endfor %}

      {% endif %}


      <div class="box">
        <div class="box-header">
          <h2>Edit Category</h2>
          <small>Edit New Category , To Associate With Products</small>
          <!-- <button class="md-btn md-raised m-b-sm w-xl green pull-right">Add Category</button> -->
        </div>
        <div class="box-divider m-a-0"></div>
        <div class="box-body">
          <form role="form" method="post">
          {% csrf_token %}
             {{ form.as_p }}
             <div class="form-group row m-t-lg">
              <div class="col-sm-4 col-sm-offset-2">
                <button type="button" class="btn white">Cancel</button>
                <button type="submit" class="btn primary">Save</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  		</div>
  	</div>
  
 {% block scripts %}
      {{ block.super }}    
      {{ form.media }}     
  {% endblock %}

  <script type="text/javascript">
  $(function(){

    $("#activeswitch").Sswitch({
      onSwitchChange: function() {
      }
    });  
  });

  </script>

  {% endblock %}

product/templates/product/create.html
{% extends 'base.html' %}
{% block title %}Create Product{% endblock %}

	{% block content %}
	<div class="padding">
  		<div class="row">
  	 <div  class="col-md-10">
      <div class="box">
        <div class="box-header">
          <h2>Create Product</h2>
          <small>* Enable Tag Is Currently Not Used , Will Be Used For Future Enhancement Of The System</small>
        </div>
        <div class="box-divider m-a-0"></div>
        <div class="box-body">
          <form role="form">
          {% csrf_token %}
            <div class="form-group row">
              <label for="inputEmail3" class="col-sm-2 form-control-label">Item Title</label>
              <div class="col-sm-10">
                <input type="text" class="md-input" id="inputEmail3" placeholder="Title">
              </div>
            </div>
            <div class="form-group row">
              <label for="inputPassword3" class="col-sm-2 form-control-label">Description</label>
              <div class="col-sm-10">
                <input type="text" class="md-input" id="inputPassword3" placeholder="Description">
              </div>
            </div>
            <div class="form-group row m-t-md">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn primary">Sign in</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  		</div>
  	</div>
	{% endblock %}

product/templates/product/create_form.html
{% extends 'base.html' %}
{% block title %}Create Product{% endblock %}


	{% block content %}
  
	<div class="padding">
  		<div class="row">
  	 <div  class="col-md-10">
    
      {% if messages %}
  
        {% for message in messages %}
        <script type="text/javascript">
        $(function(){
          
            $.notify("{{ message }}", { showProgressbar: false,type: 'success' });
         
        });
        </script>
        {% endfor %}

      {% endif %}


      <div class="box">
        <div class="box-header">
          <h2>Create Product</h2>
          <small>*Enable Tag Is Currently Not Used , Will Be Used For Future Enhancement Of The System</small>
          <!-- <button class="md-btn md-raised m-b-sm w-xl green pull-right">Add Category</button> -->
        </div>
        <div class="box-divider m-a-0"></div>
        <div class="box-body">
          <form role="form" method="post">
          {% csrf_token %}
             {{ form.as_p }}
             <div class="form-group row m-t-lg">
              <div class="col-sm-4 col-sm-offset-2">
                <button type="button" class="btn white">Cancel</button>
                <button type="submit" class="btn primary">Save</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  		</div>
  	</div>
  
  {% block scripts %}
      {{ block.super }}    
      {{ form.media }}     
  {% endblock %}

  <script type="text/javascript">
  $(function(){

    $("#activeswitch").Sswitch({
      onSwitchChange: function() {
      }
    });
   
    $('select').select2({
      placeholder: 'Select One Option'
    });
  
  });

  </script>

<style type="text/css">
  #id_category{
        min-width: 300px;
        display: block;
  }
  .select2-container {
    display: block;
  }
</style>



  {% endblock %}

product/templates/product/create_supplier.html
{% extends 'base.html' %}
{% block title %}Create Supplier{% endblock %}


	{% block content %}

	<div class="padding">
  		<div class="row">
  	 <div  class="col-md-10">

      {% if messages %}

        {% for message in messages %}
        <script type="text/javascript">
        $(function(){

            $.notify("{{ message }}", { showProgressbar: false,type: 'success' });

        });
        </script>
        {% endfor %}

      {% endif %}


      <div class="box">
        <div class="box-header">
          <h2>Create Supplier</h2>
          <small></small>
          <!-- <button class="md-btn md-raised m-b-sm w-xl green pull-right">Add Category</button> -->
        </div>
        <div class="box-divider m-a-0"></div>
        <div class="box-body">
          <form role="form" method="post">
          {% csrf_token %}
             {{ form.as_p }}
             <div class="form-group row m-t-lg">
              <div class="col-sm-4 col-sm-offset-2">
                <button type="button" class="btn white">Cancel</button>
                <button type="submit" class="btn primary">Save</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  		</div>
  	</div>

 {% block scripts %}
      {{ block.super }}
      {{ form.media }}
  {% endblock %}

  {% endblock %}

product/templates/product/edit.html
{% extends 'base.html' %}
{% block title %}Edit Product{% endblock %}


    {% block content %}
  
    <div class="padding">
        <div class="row">
     <div  class="col-md-10">
      <div class="box">
        <div class="box-header">
          <h2>Edit Product</h2>
          <small>Edit Product Carefully</small>
        </div>
        <div class="box-divider m-a-0"></div>
        <div class="box-body">
          <form role="form" method="post">
          {% csrf_token %}
             {{ form.as_p }}
             <button type="submit" class="save btn btn-default">Save</button>
          </form>
        </div>
      </div>
    </div>
        </div>
    </div>
  
  {% block scripts %}
      {{ block.super }}    
      {{ form.media }}     
  {% endblock %}

  <script type="text/javascript">
  $(function(){

    $("#activeswitch").Sswitch({
      onSwitchChange: function() {
      }
    });
  
  });

  </script>





  {% endblock %}

product/templates/product/edit_supplier.html
{% extends 'base.html' %}
{% block title %}Edit Category{% endblock %}


	{% block content %}
  
	<div class="padding">
  		<div class="row">
  	 <div  class="col-md-10">
    
      {% if messages %}
  
        {% for message in messages %}
        <script type="text/javascript">
        $(function(){
          
            $.notify("{{ message }}", { showProgressbar: false,type: 'success' });
         
        });
        </script>
        {% endfor %}

      {% endif %}


      <div class="box">
        <div class="box-header">
          <h2>Edit Supplier</h2>
          <small></small>
          <!-- <button class="md-btn md-raised m-b-sm w-xl green pull-right">Add Category</button> -->
        </div>
        <div class="box-divider m-a-0"></div>
        <div class="box-body">
          <form role="form" method="post">
          {% csrf_token %}
             {{ form.as_p }}
             <div class="form-group row m-t-lg">
              <div class="col-sm-4 col-sm-offset-2">
                <button type="button" class="btn white">Cancel</button>
                <button type="submit" class="btn primary">Save</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  		</div>
  	</div>
  
 {% block scripts %}
      {{ block.super }}    
      {{ form.media }}     
  {% endblock %}

  <script type="text/javascript">
  $(function(){

    $("#activeswitch").Sswitch({
      onSwitchChange: function() {
      }
    });  
  });

  </script>

  {% endblock %}

product/templates/product/manage.html
{% extends 'base.html' %}
{% load table_tags %}
{% load static %}
{% block title %}Manage Product{% endblock %}

{% block content %}

    {% if messages %}

        {% for message in messages %}
        <script type="text/javascript">
        $(function(){

            $.notify("{{ message }}", { showProgressbar: false,type: 'success' });

        });
        </script>
        {% endfor %}

      {% endif %}


	<div class="padding">
  		<div class="row">
  	 <div  class="col-md-12">
      <div class="box">
        <div class="box-header">
            <h2>Manage Products</h2>
            <a href="{% url 'product:create' %}" class="label primary"><i class="fa fa-plus"></i> New Product</a>
        </div>
        <div class="box-divider m-a-0"></div>
        <div class="box-body">
          {% render_table item %}
        </div>
      </div>
    </div>
  		</div>
  	</div>

	{% endblock %}

product/templates/product/manage_category.html
{% extends 'base.html' %}
{% load table_tags %}
{% load static %}
{% block title %}Manage Category{% endblock %}

{% block content %}

{% if messages %}

        {% for message in messages %}
        <script type="text/javascript">
        $(function(){

            $.notify("{{ message }}", { showProgressbar: false,type: 'success' });

        });
        </script>
        {% endfor %}

      {% endif %}

	<div class="padding">
  		<div class="row">
  	 <div  class="col-md-12">
      <div class="box">
        <div class="box-header">
          <h2>Manage Category</h2>
          <a href="{% url 'product:create_category' %}" class="label primary"><i class="fa fa-plus"></i> New Category</a>
        </div>
        <div class="box-divider m-a-0"></div>
        <div class="box-body">
          {% render_table item %}
        </div>
      </div>
    </div>
  		</div>
  	</div>

	{% endblock %}

product/templates/product/manage_supplier.html
{% extends 'base.html' %}
{% load table_tags %}
{% load static %}
{% block title %}Manage Supplier{% endblock %}

{% block content %}

{% if messages %}

        {% for message in messages %}
        <script type="text/javascript">
        $(function(){

            $.notify("{{ message }}", { showProgressbar: false,type: 'success' });

        });
        </script>
        {% endfor %}

      {% endif %}

	<div class="padding">
  		<div class="row">
  	 <div  class="col-md-12">
      <div class="box">
        <div class="box-header">
          <h2>Manage Supplier</h2>
          <a href="{% url 'product:create_supplier' %}" class="label primary"><i class="fa fa-plus"></i> New Supplier</a>
        </div>
        <div class="box-divider m-a-0"></div>
        <div class="box-body">
          {% render_table item %}
        </div>
      </div>
    </div>
  		</div>
  	</div>

	{% endblock %}